# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/rerost/playground
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t rerost/playground:`git rev-parse HEAD` .
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/rerost/playground
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker push rerost/playground:`git rev-parse HEAD`

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          context: docker push
