apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  namespace: playground
  labels:
    app: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: rerost/playground:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
